### ISSUE TITLE
Use "chrome.storage" API, advantage: settings will be sync'd

### ISSUE THREAD

**Issue by ddidderr** [hultqvist/Kiss#17]
Changing the storage API from localStorage to the `chrome.storage` API will allow Chrome to sync all the settings and filters. That would be awesome! :)

https://developer.chrome.com/extensions/storage.html

**Comment by K1773R** [comment]
what is the limit of an the object?

**Comment by hultqvist** [comment]
You should be able to find it here.
https://developer.chrome.com/extensions/storage#property-sync

From what I recall, I hit the limit quite fast with only a few hundred
filter rows.

The problem is that each storage unit is too small to fit all filter rows
in one, the solution is most likely to split them up in a way that we still
can find them.
Den 18 jul 2015 17:16 skrev "K1773R" <notifications@github.com>:
