### ISSUE TITLE
->* clear overrides even non cross-domain requests

### ISSUE THREAD

**Issue by christopherliu** [hultqvist/Kiss#24]
I had a filter setting localhost -> * to clear. Prior to this, requests for pages on localhost would include the cookie header; however, after this, requests for pages on localhost (not scripts or CSS but the original page) would not include the cookie header, even if "Allow request within same domain even though "block:*>domain" is set." was checked in the options header.

**Comment by hultqvist** [comment]
The keyword is **block** in the special setting `Allow requests within the same domain even though "block:*>domain" is set.` only applies to completely blocking filters.

Source code for the logic is found [here](https://github.com/hultqvist/Kiss/blob/e186997a95dcbddc750cbc4c877e875b2d63f30d/script/background.js#L173)

Since your first filter is not blocking the request the other option won't affect it and the request will be filtered using the `clear` action.

I'm still skeptical to this feature and suggest people add specific filters for when they need to access a page otherwise blocked when used as a third party site.

I leave this issue open if you have any ideas on how it could be modified, especially what the logic and the options would be.

**Comment by christopherliu** [comment]
Hmm. Well, ignoring the ` Allow requests within the same domain even though "block:*>domain" is set` feature, here's what I had before:

[No filters]
Result: Localhost passes to localhost (no cookie clearing, default action)

[localhost->*: clear]
Result: Localhost clears to localhost (cookie clearing)

I think I expected that a default rule with a specific target would take precedence over a custom rule with a wildcard target. That was more hopeful intuition than logic though. :)

Question: Who clears/blocks same domain requests? What's the use case for that ability?

**Comment by hultqvist** [comment]
Yes the idea is that more specific rules take precedence.

The default action setting only applies if there is no matching filters at all.

Once you add the first filter `[localhost->*: clear]` it takes over any default settings and you would also need to add another one `[localhost->localhost: pass]`

The use case to clear/block the same domain request is useful if you run a whitelist approach.
Let's say you add a filter `[mywebsite->static.weatherwidget.com: clear]` because you don't want the site to set any cookies. Now if that is loaded in an iframe the weather widget could in turn call other resources within its own domain and now those would be applicable to the default same domain option.

mysite.com -(clear)-> static.weatherwidget.com -(default: pass)-> static.weatherwidget.com

In this scenario the cookies would be set on static.weatherwidget.com even though you used the clear filter on the first request.

**Comment by christopherliu** [comment]
Very interesting. I'll give this some more thought, thanks.

**Comment by hultqvist** [comment]
let me know if you have any more questions

**Comment by christopherliu** [comment]
OK. Hmmmm, let me think...I think what I was confused by is that the (clear) policy applies to both referers and cookies. Referers are inherently cross-domain; the purpose of blocking referers is to reduce the amount of knowledge a third party site has about my web browsing. Cookies are inherently single-domain; by blocking cookies we prevent a third party site from retaining knowledge about me.

Let's say I wanted to watch a video embedded on a website. The policy I'd need would be:
`website -(clear)-> video site`

This would block the referrer, so that the video site wouldn't recognize who referred me to the video. So far so good.

With cookies though, there's a problem. Presumably I'm logged on to this video site already, and have cookies for it. If (clear) clears the cookies, we're basically pretending that "I am a complete stranger asking to see your video."
`website -(clear)-> video site -(clear)-> video site`

Which is actually pretty cool; however, now I can't log into the video website at all:
`video site -(clear)-> video site`

At this point, I might as well be blocking cookies in Chrome itself anyway.

On the other hand, if (pass) reenables the cookies, we aren't really blocking cookies at all, as you said before:
`website -(clear)-> video site -(pass: overrides)-> video site`

I think I'll work around this by enabling cookies in pass, however I leave it up in case you have any other ideas. Thanks for your help!

**Comment by hultqvist** [comment]
Your interpretation of "clear" is correct assuming it is the one that comes by default.

However you are free to modify it on the options page and add several more `actions` which you configure how you like.

For example you can...
* change "clear" so that it only clear referer and keep cookie
* add another "big-clear" that clear both referer and cookie
* add yet another "no-cookie" that clear cookies only
